<a href="https://colab.research.google.com/github/PG-18/Pytorch-1/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


# Creating tensors


In [2]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
 MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

RANDOM TENSORS


Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to be better represent the data.


Start with random numbers->look at data->update random numbers


In [16]:
#Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7828, 0.6838, 0.1448, 0.7195],
        [0.2745, 0.5800, 0.2119, 0.4236],
        [0.7486, 0.6949, 0.7885, 0.3761]])

In [17]:
random_tensor=torch.rand(10,10)
random_tensor

tensor([[0.2614, 0.6679, 0.7584, 0.2553, 0.4891, 0.4480, 0.4961, 0.6204, 0.1722,
         0.7650],
        [0.8909, 0.1770, 0.1592, 0.3853, 0.0929, 0.1205, 0.3703, 0.4983, 0.8676,
         0.4525],
        [0.1686, 0.0539, 0.3260, 0.7742, 0.1177, 0.9601, 0.9971, 0.5131, 0.6900,
         0.0438],
        [0.2991, 0.0146, 0.6783, 0.2303, 0.3962, 0.4472, 0.7545, 0.8230, 0.1594,
         0.7330],
        [0.8754, 0.4919, 0.8018, 0.4124, 0.9251, 0.4659, 0.8617, 0.4979, 0.3760,
         0.9021],
        [0.9579, 0.1182, 0.3161, 0.3199, 0.9029, 0.9709, 0.2995, 0.2570, 0.5222,
         0.9452],
        [0.8977, 0.2946, 0.6234, 0.7508, 0.5148, 0.9574, 0.7287, 0.6798, 0.8035,
         0.4161],
        [0.4130, 0.9742, 0.2059, 0.1339, 0.8953, 0.9653, 0.0216, 0.7735, 0.0852,
         0.2828],
        [0.3061, 0.0280, 0.2199, 0.7626, 0.8422, 0.0091, 0.8785, 0.2328, 0.4894,
         0.3643],
        [0.7805, 0.4755, 0.3762, 0.8539, 0.1774, 0.0665, 0.5291, 0.3873, 0.0313,
         0.8598]])

In [18]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))#height,width,colour channelS (R,G,B)
random_image_size_tensor.shape,
random_image_size_tensor.ndim

3

In [19]:
torch.rand(3,3)

tensor([[0.9856, 0.3796, 0.7853],
        [0.7787, 0.4123, 0.0775],
        [0.0258, 0.2599, 0.2298]])

ZEROS AND ONES


In [20]:
#Create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

Creating a  range of tensor and tensors like


In [23]:
 #Use torch.range()
 one_to_ten=torch.arange(start=1,end=1000,step=77)
 one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [24]:
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros
#zeros like 1 to 10


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPES
Note: Tensor datatypes is one of the 3 big errors you qill run into Pytorch & deeplearning.
1.Tensors not right datatype.
2.Tensors not right shape.
3.Tensors not on the right device.

In [26]:
#Float 32 tensor

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #what datatype is your tensor (e.g: float32 or float16)
                             device=None,#what device is your tensor on
                             requires_grad=False)#whether or not to track gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_16_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [35]:
#Getting information from tensors
#1.Tensors not right datatype. - To do get datatype from a tensor,can use 'tensor.dtype'
#2.Tensors not right shape. -To get shape from tensor,can use 'tensor.shape'
#3.Tensors not on the right device.-To get device from a tensor,can use 'tensor.device'

In [36]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4577, 0.5792, 0.5419, 0.1403],
        [0.0917, 0.2571, 0.9995, 0.1501],
        [0.8258, 0.4144, 0.6766, 0.7198]])

In [37]:
some_tensor.size()

torch.Size([3, 4])

In [38]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device the tensor is on:{some_tensor.device} ")

tensor([[0.4577, 0.5792, 0.5419, 0.1403],
        [0.0917, 0.2571, 0.9995, 0.1501],
        [0.8258, 0.4144, 0.6766, 0.7198]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device the tensor is on:cpu 


Manipulating Tensors(Tensor Operations)
Tensor operations include:
*Addition
*Subtraction
*Multiplication(element-wise)
*Division
*Matrix multiplication

In [39]:
#create tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [40]:
#multiply by 10
tensor*10

tensor([10, 20, 30])

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
#Subtract 10
tensor-10

tensor([-9, -8, -7])

In [43]:
#Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor,15)

tensor([16, 17, 18])

#Matrix Multiplication
#Two main ways of performing multiplication in neural networks and deep learning:
#1.Element wise multiplication
#2.Matrix multiplication(dot product)
#There are two main rules that performs matrix multiplication needs to satisfy:
1.The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
*(2,3) @ (3,2)' will work
* (3,2) @ (2,3) will work
2.The resulting matrix has the shape of the outer dimensions:
*(2,3) @ (3,2) ->(2,2)
*(3,2) @ (2,3)->(3,3)


In [45]:
#ELEMENT WISE MULTIPLICATION
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [46]:
#usinf inbuilt func
torch.matmul(tensor,tensor)

tensor(14)

In [47]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.16 ms, sys: 2.04 ms, total: 3.2 ms
Wall time: 3.12 ms


In [53]:
### one of the most common errors in deep learning :SHAPE ERRORS
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7, 10],
                      [8, 11],
                      [9, 12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
tensor_A.shape,tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues,we can manipulate the shape of one of our tensors using a transpose.A **tranpose** switches the axes or dimensions of given tensor.

> Indented block



In [55]:
tensor_A.shape,tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [56]:
tensor_B.shape, tensor_B

(torch.Size([3, 2]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [57]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [58]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A={tensor_A.shape},tensor_B.T={tensor_B.T.shape}")
print(f"New shapes: tensor_A={tensor_A.shape}(same shape as above ),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape: {output.shape}")


Original shapes: tensor_A=torch.Size([3, 2]),tensor_B.T=torch.Size([2, 3])
New shapes: tensor_A=torch.Size([3, 2])(same shape as above ),tensor_B.T=torch.Size([2, 3])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape: torch.Size([3, 3])


FIND THE MIN,MAX,MEAN,SUM, ETC(TENSOR AGGREGATION)

In [59]:
#create tensor
x=torch.arange(0,100,10)
x
x.dtype

torch.int64

In [60]:

#FIND MIN
torch.min(x),x.min()

(tensor(0), tensor(0))

In [61]:
#Find the max
torch.max(x),x.max()


(tensor(90), tensor(90))

In [62]:
#FIND MEAN NOTE: The torch.mean() function requires a tensor of float32 datatype so changing the type
torch.mean(x.type(torch.float32)) #changing the type

tensor(45.)

In [63]:
#Find sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

FINDING THE POSITIONAL MIN AND MAX

In [64]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
x.argmin() #Find the position in tensor that has the minimum value with the argmin()---> return index position of the target tensor where the minimum value occurs

tensor(0)

In [66]:
x[0]

tensor(0)

In [67]:
# Find the position in tensor that has the maximum value with the argmax()---> return index position of the target tensor where the maximum value occurs
x.argmax()

tensor(9)

#RESHAPING,STACKING,SQUEEZING,UNSQUEEZING TENSORS

*Reshaping-Reshapes an input tensor to a defined shape
*View-Return view of an input tensor of certain shape but keep the same memory as the original tensor
*Stacking-Combine multiple tensors on top of each other(vstack) or side by side(hstack)
*Squeeze-Removes all '1' dimensions from a tensor



In [68]:
#Let"s create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [69]:
#Add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [70]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:

#Change the view
z=x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
# Changing z changes x (Because a view of a tensor shares the same memory as the original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [73]:
#Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [74]:

x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [75]:
#torch.squeeze()-removes all single dimensions from a target tensor
x_reshaped
x_reshaped.shape

torch.Size([1, 9])

In [76]:
#torch.squeeze()-removes all single dimensions from a target tensor

print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape:{x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")



Previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape:torch.Size([1, 9])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [77]:

x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
x_reshaped.squeeze().shape

torch.Size([9])

In [79]:
#torch.unsqueeze()--Adds a single dimension to a target tensor to a target tensor at a specific dimensions
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")




Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

New tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape:torch.Size([9, 1])


In [80]:
#torch.permute-rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3)) #[height,width,color_channels]


 #Permute the original tensor to rearrange the axis (or dim) order
x_permuted=x_original.permute(2,0,1)

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")   #[colour_channels,height,width]



Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [81]:
x_original

tensor([[[0.5855, 0.4367, 0.7037],
         [0.9647, 0.7454, 0.4800],
         [0.2309, 0.1966, 0.4494],
         ...,
         [0.6702, 0.6160, 0.5880],
         [0.7841, 0.6325, 0.7730],
         [0.2324, 0.7391, 0.8509]],

        [[0.1875, 0.3209, 0.2783],
         [0.8401, 0.8446, 0.8204],
         [0.5953, 0.1311, 0.4848],
         ...,
         [0.8117, 0.7113, 0.6480],
         [0.6197, 0.8419, 0.0362],
         [0.8080, 0.3078, 0.3207]],

        [[0.5259, 0.4284, 0.5076],
         [0.6279, 0.9512, 0.2431],
         [0.3479, 0.3008, 0.9219],
         ...,
         [0.3743, 0.1084, 0.5977],
         [0.1090, 0.0748, 0.2867],
         [0.4979, 0.8616, 0.0092]],

        ...,

        [[0.0337, 0.5237, 0.0647],
         [0.6982, 0.2769, 0.1731],
         [0.6018, 0.4118, 0.1383],
         ...,
         [0.3202, 0.7046, 0.7689],
         [0.1102, 0.3246, 0.9583],
         [0.8006, 0.3471, 0.3027]],

        [[0.7749, 0.4343, 0.1387],
         [0.1213, 0.7673, 0.1404],
         [0.

In [82]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

#Indexing(selecting data from tensors)
###Indexing with Pytorch is similar to indexing with NumPy

In [83]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [84]:
x.shape

torch.Size([1, 3, 3])

In [85]:
x.reshape(1,3,3)


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [86]:
# Lets index on our new tensor
x[0][0]

tensor([1, 2, 3])

In [87]:
# Let's index on the middle bracket(dim=1)
x[0,0]


tensor([1, 2, 3])

In [88]:
#Let's index on the most inner bracket(last dimnsion)
x[0][1][1]

tensor(5)

In [89]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [90]:
# Get all values 0th and 1st dimensions but only index 1 and 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [91]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [92]:
#Get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0,1,:]

tensor([4, 5, 6])

In [93]:
#Index on x to return
print(x[0][2][2])

#Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


#PyTorch tensors and NumPy
NumPy is a popular scientific Python numerical computing library.
and because of this ,Pytorch has functionality to interact with it.
* Data in NumPy,want in Pytorch tensor-"torch.from_numpy(ndarray)"
*Pytorch tensor-> Numpy->"torch.Tensor.numpy()"

In [94]:
#NumPy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
array.dtype

dtype('float64')

In [96]:
#Change the value of array,what will this do to 'tensor'
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
#Tensor to NumPy ARRAY
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducability(trying to take random out of random)
In short how a neural network learns:
**start with a random numbers-> tensor operations->update random numbers to try and make them of the data->again->again->...**
*To reduce the randomness in neural networks and Pytorch comes the concept of **random seed***

In [98]:
torch.rand(3,3)

tensor([[3.3091e-01, 2.3263e-02, 8.0207e-01],
        [3.1062e-01, 3.5141e-02, 1.6755e-04],
        [9.1511e-01, 5.5983e-01, 2.2449e-01]])

In [106]:
import torch
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.3859, 0.6061, 0.0447, 0.9365],
        [0.3264, 0.3164, 0.3537, 0.2412],
        [0.0201, 0.6736, 0.6413, 0.2283]])
tensor([[0.1007, 0.3849, 0.1698, 0.0895],
        [0.0481, 0.3217, 0.1208, 0.6744],
        [0.2454, 0.1364, 0.4224, 0.0256]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [108]:
#Let's make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


EXTRA RESOURCES for REPRODUCIBILITY
*https://pytorch.org/docs/stable/notes/randomness.html

###Running Tensors and PyTorch objects on the GPUs(and making faster computations)
GPUs=faster computations on numbers thanks to CUDA+NVIDIA hardware+ PyTorch working behind the scenes to make everything hunky dory(good)

In [110]:

!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [111]:
# @title Default title text
#CHECK FOR GPU ACCESS WITH PYTORCH
import torch
torch.cuda.is_available()


False