In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


# Creating tensors


In [6]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])