<a href="https://colab.research.google.com/github/PG-18/Pytorch-1/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


# Creating tensors


In [30]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [31]:
scalar.ndim

0

In [32]:
scalar.item()

7

In [33]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [34]:
vector.ndim

1

In [35]:
vector.shape

torch.Size([2])

In [36]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [37]:
MATRIX.ndim

2

In [38]:
 MATRIX[1]

tensor([ 9, 10])

In [39]:
MATRIX.shape

torch.Size([2, 2])

In [40]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [41]:
TENSOR.ndim

3

In [42]:
TENSOR.shape

torch.Size([1, 3, 3])

In [43]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

RANDOM TENSORS


Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to be better represent the data.
Start with random numbers->look at data->update random numbers


In [44]:
#Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6791, 0.3063, 0.9485, 0.4789],
        [0.1699, 0.2802, 0.7528, 0.3841],
        [0.6988, 0.7790, 0.2619, 0.6374]])

In [45]:
random_tensor=torch.rand(10,10)
random_tensor

tensor([[0.0132, 0.8351, 0.4573, 0.8907, 0.0629, 0.5479, 0.7108, 0.4690, 0.0223,
         0.0327],
        [0.3807, 0.1255, 0.3623, 0.3189, 0.4900, 0.0066, 0.8738, 0.9872, 0.9752,
         0.6005],
        [0.5132, 0.5388, 0.4218, 0.1966, 0.2268, 0.5068, 0.9109, 0.0804, 0.3621,
         0.4247],
        [0.1169, 0.1405, 0.4797, 0.1617, 0.9736, 0.8070, 0.2519, 0.5593, 0.9041,
         0.5895],
        [0.6430, 0.6195, 0.9213, 0.4472, 0.0488, 0.2900, 0.3705, 0.6366, 0.0895,
         0.9900],
        [0.2150, 0.9902, 0.3808, 0.9287, 0.3776, 0.5543, 0.2856, 0.0183, 0.1871,
         0.8477],
        [0.4113, 0.8917, 0.1116, 0.0276, 0.7257, 0.1258, 0.2084, 0.6814, 0.5216,
         0.9846],
        [0.3269, 0.5729, 0.0952, 0.0957, 0.1789, 0.8210, 0.6203, 0.4272, 0.2806,
         0.7047],
        [0.6885, 0.9506, 0.1147, 0.4723, 0.1525, 0.7951, 0.5522, 0.4408, 0.9667,
         0.4712],
        [0.3149, 0.3920, 0.1787, 0.1967, 0.4253, 0.0595, 0.1027, 0.2034, 0.5132,
         0.3273]])

In [46]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))#height,width,colour channelS (R,G,B)
random_image_size_tensor.shape,
random_image_size_tensor.ndim

3

In [47]:
torch.rand(3,3)

tensor([[0.8341, 0.6917, 0.2667],
        [0.9295, 0.8380, 0.1664],
        [0.3023, 0.4569, 0.5844]])

ZEROS AND ONES


In [48]:
#Create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
ones.dtype

torch.float32

Creating a  range of tensor and tensors like


In [51]:
 #Use torch.range()
 one_to_ten=torch.arange(start=1,end=1000,step=77)
 one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [52]:
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros
#zeros like 1 to 10


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPES
Note: Tensor datatypes is one of the 3 big errors you qill run into Pytorch & deeplearning.
1.Tensors not right datatype.
2.Tensors not right shape.
3.Tensors not on the right device.

In [54]:
#Float 32 tensor

In [55]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [56]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [58]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #what datatype is your tensor (e.g: float32 or float16)
                             device=None,#what device is your tensor on
                             requires_grad=False)#whether or not to track gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [59]:
float_32_tensor.dtype

torch.float32

In [61]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)