<a href="https://colab.research.google.com/github/PG-18/Pytorch-1/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


# Creating tensors


In [2]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
 MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

RANDOM TENSORS


Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to be better represent the data.
Start with random numbers->look at data->update random numbers


In [16]:
#Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7063, 0.6740, 0.5340, 0.7234],
        [0.6203, 0.0837, 0.9121, 0.2648],
        [0.5011, 0.4862, 0.5836, 0.9215]])

In [17]:
random_tensor=torch.rand(10,10)
random_tensor

tensor([[6.2099e-01, 1.9331e-01, 1.1553e-01, 2.2690e-01, 3.7291e-01, 7.7371e-01,
         9.6091e-01, 7.1705e-01, 5.9691e-01, 1.8637e-01],
        [2.5029e-03, 4.1251e-01, 1.6330e-01, 6.0180e-01, 7.4490e-01, 6.7516e-01,
         9.1884e-01, 4.6395e-01, 3.9475e-01, 9.4927e-01],
        [4.8613e-01, 1.6258e-01, 9.0741e-01, 6.9748e-01, 7.7997e-01, 1.0699e-01,
         1.6527e-01, 8.3559e-01, 4.2314e-01, 1.2209e-01],
        [1.1060e-01, 9.3265e-01, 3.8234e-01, 9.4182e-01, 9.5535e-01, 2.0944e-01,
         5.5494e-01, 4.8129e-01, 4.4082e-01, 3.3879e-01],
        [7.8320e-01, 9.6237e-01, 5.1892e-01, 4.9140e-01, 9.3430e-01, 9.3607e-03,
         7.9541e-01, 6.1687e-01, 6.6752e-01, 5.6632e-01],
        [9.3651e-01, 9.6214e-01, 7.7110e-01, 2.0547e-01, 2.4856e-01, 3.1614e-01,
         6.2615e-01, 1.1906e-01, 9.0647e-01, 3.7891e-01],
        [4.1575e-01, 9.8697e-01, 8.9196e-01, 9.1049e-01, 1.5627e-01, 5.6331e-01,
         8.9242e-01, 9.3513e-01, 3.6999e-01, 4.3543e-01],
        [6.3647e-02, 1.7515

In [18]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))#height,width,colour channelS (R,G,B)
random_image_size_tensor.shape,
random_image_size_tensor.ndim

3

In [19]:
torch.rand(3,3)

tensor([[0.8629, 0.6034, 0.8082],
        [0.5592, 0.5198, 0.0659],
        [0.5646, 0.1801, 0.5561]])

ZEROS AND ONES


In [20]:
#Create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

Creating a  range of tensor and tensors like


In [23]:
 #Use torch.range()
 one_to_ten=torch.arange(start=1,end=1000,step=77)
 one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [24]:
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros
#zeros like 1 to 10


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPES
Note: Tensor datatypes is one of the 3 big errors you qill run into Pytorch & deeplearning.
1.Tensors not right datatype.
2.Tensors not right shape.
3.Tensors not on the right device.

In [26]:
#Float 32 tensor

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #what datatype is your tensor (e.g: float32 or float16)
                             device=None,#what device is your tensor on
                             requires_grad=False)#whether or not to track gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_16_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [35]:
#Getting information from tensors
#1.Tensors not right datatype. - To do get datatype from a tensor,can use 'tensor.dtype'
#2.Tensors not right shape. -To get shape from tensor,can use 'tensor.shape'
#3.Tensors not on the right device.-To get device from a tensor,can use 'tensor.device'

In [36]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4296, 0.1548, 0.9265, 0.5962],
        [0.9166, 0.9278, 0.2004, 0.1632],
        [0.0599, 0.5824, 0.2494, 0.4859]])

In [37]:
some_tensor.size()

torch.Size([3, 4])

In [38]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device the tensor is on:{some_tensor.device} ")

tensor([[0.4296, 0.1548, 0.9265, 0.5962],
        [0.9166, 0.9278, 0.2004, 0.1632],
        [0.0599, 0.5824, 0.2494, 0.4859]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device the tensor is on:cpu 


Manipulating Tensors(Tensor Operations)
Tensor operations include:
*Addition
*Subtraction
*Multiplication(element-wise)
*Division
*Matrix multiplication

In [39]:
#create tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [40]:
#multiply by 10
tensor*10

tensor([10, 20, 30])

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
#Subtract 10
tensor-10

tensor([-9, -8, -7])

In [43]:
#Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor,15)

tensor([16, 17, 18])

##Matrix Multiplication
#Two main ways of performing multiplication in neural networks and deep learning:
#1.Element wise multiplication
#2.Matrix multiplication(dot product)
#There are two main rules that performs matrix multiplication needs to satisfy:
1.The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
*(2,3) @ (3,2)' will work
* (3,2) @ (2,3) will work
2.The resulting matrix has the shape of the outer dimensions:
*(2,3) @ (3,2) ->(2,2)
*(3,2) @ (2,3)->(3,3)


In [45]:
#ELEMENT WISE MULTIPLICATION
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [46]:
#usinf inbuilt func
torch.matmul(tensor,tensor)

tensor(14)

In [47]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.07 ms, sys: 0 ns, total: 1.07 ms
Wall time: 1.29 ms


In [56]:
### one of the most common errors in deep learning :SHAPE ERRORS
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7, 10],
                      [8, 11],
                      [9, 12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [57]:
tensor_A.shape,tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues,we can manipulate the shape of one of our tensors using a transpose.A tranpose switches the axes or dimensions of given tensor.

In [58]:
tensor_A.shape,tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [59]:
tensor_B.shape, tensor_B

(torch.Size([3, 2]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [61]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [62]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A={tensor_A.shape},tensor_B.T={tensor_B.T.shape}")
print(f"New shapes: tensor_A={tensor_A.shape}(same shape as above ),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape: {output.shape}")


Original shapes: tensor_A=torch.Size([3, 2]),tensor_B.T=torch.Size([2, 3])
New shapes: tensor_A=torch.Size([3, 2])(same shape as above ),tensor_B.T=torch.Size([2, 3])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape: torch.Size([3, 3])


FIND THE MIN,MAX,MEAN,SUM, ETC(TENSOR AGGREGATION)

In [67]:
#create tensor
x=torch.arange(0,100,10)
x
x.dtype

torch.int64

In [68]:
#FIND MIN
torch.min(x),x.min()

(tensor(0), tensor(0))

In [69]:
#Find the max
torch.max(x),x.max()


(tensor(90), tensor(90))

In [76]:
#FIND MEAN NOTE: The torch.mean() function requires a tensor of float32 datatype so changing the type
torch.mean(x.type(torch.float32)) #changing the type

tensor(45.)

In [77]:
#Find sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

FINDING THE POSITIONAL MIN AND MAX

In [78]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
x.argmin() #Find the position in tensor that has the minimum value with the argmin()---> return index position of the target tensor where the minimum value occurs

tensor(0)

In [82]:
x[0]

tensor(0)

In [83]:
# Find the position in tensor that has the maximum value with the argmax()---> return index position of the target tensor where the maximum value occurs
x.argmax()

tensor(9)